language: php
sudo: required
dist: trusty
php:
  - 7.1
  - 7.2

env:
  global:
    - CORE_BRANCH=master
    - APP_NAME=search_lucene

  matrix:
    - DB=sqlite

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

before_install:
#  - composer install
  - which php
  - more `which pecl`
  - which phpize
  - bash tests/.travis/before_install.sh $APP_NAME $CORE_BRANCH $DB
  - cd ../core
  - php occ app:enable $APP_NAME

script:
  # Test lint
  - cd apps/$APP_NAME
  - sh -c "if [ '$DB' = 'sqlite' ]; then ant test; fi"

  # Run phpunit tests
  - cd tests/unit
  - ../../../../lib/composer/bin/phpunit --configuration phpunit.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  include:
    - php: 7.1
      env: DB=mysql
    - php: 7.1
      env: DB=pgsql
    - php: 7.1
      env: DB=oracle
    - php: 5.6
      env: DB=mysql CORE_BRANCH=stable10
    - php: 7.0
      env: DB=mysql CORE_BRANCH=stable10

  fast_finish: true
